name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - '**'

jobs:
  commitlint:
    name: Lint commit messages
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ—ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ“„ Check commits messages
        uses: wagoid/commitlint-github-action@v5

  types:
    name: Check types
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [1.0.1]

    steps:
      - name: ğŸ—ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ—ï¸ Use Bun.js ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: ğŸ“¦ Install dependencies
        run: bun i --frozen-lockfile

      - name: ğŸ› ï¸ Check types
        run: bun type-check

  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [1.0.1]

    steps:
      - name: ğŸ—ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ—ï¸ Use Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: ğŸ“¦ Install dependencies
        run: bun i --frozen-lockfile

      - name: ğŸ› ï¸ Lint
        run: bun lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [1.0.1]

    steps:
      - name: ğŸ—ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ—ï¸ Use Bun.js ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: ğŸ“¦ Install dependencies
        run: bun i --frozen-lockfile

      - name: ğŸ§ª Run tests
        run: bun test:ci
